import { Inter, Roboto_Flex } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "@/lib/registry";

// const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto_Flex({
  weight: ['400', '700'],
  subsets: ['latin'],
})

export const metadata = {
  title: "Pomosys",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry></body>
    </html>
  );
}
